import sys
from PyQt5.QtWidgets import QApplication, QWidget, QMainWindow

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(600, 600)
        self.centralwidget = QtWidgets.QWidget(Settings)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 20, 141, 20))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(430, 530, 121, 41))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(70, 80, 401, 401))
        self.tabWidget.setStyleSheet("Противник\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.Skin = QtWidgets.QWidget()
        self.Skin.setObjectName("Skin")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.Skin)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 401, 381))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_4 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout.addWidget(self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout.addWidget(self.radioButton_5)
        self.radioButton_6 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_6.setObjectName("radioButton_6")
        self.verticalLayout.addWidget(self.radioButton_6)
        self.radioButton_7 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_7.setObjectName("radioButton_7")
        self.verticalLayout.addWidget(self.radioButton_7)
        self.radioButton_8 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_8.setObjectName("radioButton_8")
        self.verticalLayout.addWidget(self.radioButton_8)
        self.tabWidget.addTab(self.Skin, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(-1, -1, 401, 381))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_2.addWidget(self.radioButton_2)
        self.radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_2.addWidget(self.radioButton)
        self.radioButton_3 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_2.addWidget(self.radioButton_3)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab_3)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(-1, -1, 401, 381))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radioButton_10 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radioButton_10.setMinimumSize(QtCore.QSize(399, 0))
        self.radioButton_10.setMaximumSize(QtCore.QSize(399, 17))
        self.radioButton_10.setIconSize(QtCore.QSize(30, 30))
        self.radioButton_10.setObjectName("radioButton_10")
        self.verticalLayout_3.addWidget(self.radioButton_10)
        self.radioButton_11 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radioButton_11.setObjectName("radioButton_11")
        self.verticalLayout_3.addWidget(self.radioButton_11)
        self.radioButton_9 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radioButton_9.setObjectName("radioButton_9")
        self.verticalLayout_3.addWidget(self.radioButton_9)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab_4)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(-1, -1, 401, 381))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.radioButton_13 = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.radioButton_13.setObjectName("radioButton_13")
        self.verticalLayout_4.addWidget(self.radioButton_13)
        self.radioButton_14 = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.radioButton_14.setObjectName("radioButton_14")
        self.verticalLayout_4.addWidget(self.radioButton_14)
        self.radioButton_12 = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.radioButton_12.setObjectName("radioButton_12")
        self.verticalLayout_4.addWidget(self.radioButton_12)
        self.tabWidget.addTab(self.tab_4, "")
        Settings.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Settings)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        Settings.setMenuBar(self.menubar)

        self.retranslateUi(Settings)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "MainWindow"))
        self.label.setText(_translate("Settings", "<html><head/><body><p><span style=\" font-size:18pt; color:#ff0000;\">Настройки игры</span></p></body></html>"))
        self.pushButton.setText(_translate("Settings", "Сохранить настройки"))
        self.tabWidget.setToolTip(_translate("Settings", "<html><head/><body><p>Герой</p><p><br/></p></body></html>"))
        self.radioButton_4.setText(_translate("Settings", "R-2 D-2"))
        self.radioButton_5.setText(_translate("Settings", "BB-8"))
        self.radioButton_6.setText(_translate("Settings", "R-4"))
        self.radioButton_7.setText(_translate("Settings", "C-3 P O"))
        self.radioButton_8.setText(_translate("Settings", "Chopper"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Skin), _translate("Settings", "Персонаж"))
        self.radioButton_2.setText(_translate("Settings", "Штурмовик"))
        self.radioButton.setText(_translate("Settings", "Штурмовик Смерти"))
        self.radioButton_3.setText(_translate("Settings", "Дроид торговой Федерации"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Settings", "Противник"))
        self.radioButton_10.setText(_translate("Settings", "Ямы"))
        self.radioButton_11.setText(_translate("Settings", "Мины"))
        self.radioButton_9.setText(_translate("Settings", "Баст-дроиды"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Settings", "Препятствия"))
        self.radioButton_13.setText(_translate("Settings", "Татуин"))
        self.radioButton_14.setText(_translate("Settings", "Эндор"))
        self.radioButton_12.setText(_translate("Settings", "Серый фон"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Settings", "Фон"))




class MyWidget(QMainWindow, Ui_Settings):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.pushButton.clicked.connect(self.run)

    def run(self):
        self.label.setText("OK")


app = QApplication(sys.argv)
ex = MyWidget()
ex.show()
sys.exit(app.exec_())
